set -g extended-keys on
set -g extended-keys-format csi-u
set -g renumber-windows on
set -g set-clipboard on

set -g status-style "#{?client_prefix,bg=colour12,bg=default}"
set -g status-format[0] "#[align=right]#[fg=colour4,bold] #h:#S #[default]"
set -g message-style "fg=colour0,bg=colour15"
set -g message-command-style "fg=colour0,bg=colour15"

bind Enter copy-mode
bind r source-file "~/.config/tmux/tmux.conf"
