# general -->
export EDITOR="nvim"
export VISUAL="nvim"
export MANPAGER='nvim +Man!'            # open manpages with vim
export MANWIDTH=999

setopt autocd                           # no need to use cd to cd into directory
autoload -U colors && colors            # enable colors
zle_highlight=('paste:none')            # don't highlight pasted text
# <--

# history --> 
HISTFILE="$XDG_CACHE_HOME/zsh/history"
HISTSIZE=10000000
SAVEHIST=10000000
setopt inc_append_history               # append to history file without having to exit shell

# move history files to appropriate locations to appropriate location
export PYTHON_HISTORY="$XDG_CACHE_HOME/python/history"
export LESSHISTFILE="$XDG_CACHE_HOME/less/history"

# use existing string to search history
autoload -Uz up-line-or-beginning-search 
autoload -Uz down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey -M viins "^[[A" up-line-or-beginning-search
bindkey -M viins "^[[B" down-line-or-beginning-search
# <--

# aliases -->
# list alias:
# - show hidden files (-A),
# - add slashes after directories (-F)
# - delete total count (sed '1d')
# - don't show .DS_Store (sed '.DS_Store'/d)
# - don't show file permissions (rest of sed command)
alias ll"=ls -ohAF --color=always | sed '1d;/.DS_Store/d;s/^.\{11\}[[:space:]]*[[:digit:]]*[[:space:]]//g'"

# make things safe and verbose
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -Ivr"
mkd() {
	mkdir -pv -- "$1" && cd -- "$1"
}

alias vim=nvim
alias python=python3

# parent directories
alias ...=../..
alias ....=../../..
alias .....=../../../..
# <--

# autocompletion -->
autoload -U compinit
compinit -d $XDG_CACHE_HOME/zsh/zcompdump  # create cache file in appropriate location
zstyle ':completion:*' cache-path "$XDG_CACHE_HOME/zsh/zcompcache"
_comp_options+=(globdots)                  # autocomplete hidden files

# candidate colors in the picker — match ll: dir=blue, symlink=magenta (files stay default)
zstyle ':completion:*' list-colors \
  'di=34' 'ln=35' 'so=32' 'pi=33' 'ex=31' \
  'bd=34;46' 'cd=34;43' 'su=30;41' 'sg=30;46' 'tw=30;42' 'ow=30;43'
# group candidates by type, with headers fzf-tab can show/switch between
zstyle ':completion:*' group-name ''
zstyle ':completion:*:descriptions' format '[%d]'
# cd: prefer real local dirs over $cdpath, and allow ../
zstyle ':completion:*:*:cd:*' tag-order local-directories directory-stack
zstyle ':completion:*' special-dirs false

# autoload -Uz chpwd_recent_dirs cdr add-zsh-hook
# add-zsh-hook chpwd chpwd_recent_dirs
# zstyle ':chpwd:*' recent-dirs-max 500
# zstyle ':completion:*' recent-dirs-insert both
# <--

# keybinds -->
# remove the keybinds to reserve it for iterm navigation
bindkey -r ^J
bindkey -r ^K
bindkey -r ^L
bindkey -r ^H
# <--

# fzf -->
export FZF_DEFAULT_OPTS='
--height=~8
--layout=reverse
--color=fg:-1,list-fg:8,bg:-1     
--color=fg+:-1:regular,bg+:7
--color=hl:11:bold,hl+:11:bold
--color=query:-1:regular,prompt:4:regular,marker:2
--color=gutter:-1,pointer:4:regular
--padding=0,0,0,1
--border=none
--pointer=" "
--marker=">"
--cycle
--no-scrollbar
--no-info
--no-separator
--preview-border=line
--color=preview-border:8
'
# source the fzf defaults (generated by fzf --zsh)
source <(fzf --zsh)
# <--

# prompt -->
fpath+=($ZDOTDIR/prompts/pure)             # add prompts/pure to fpath
export PURE_PROMPT_SYMBOL='>'
export PURE_PROMPT_VICMD_SYMBOL='<'
export PURE_GIT_UP_ARROW='↑'
export PURE_GIT_DOWN_ARROW='↓'
autoload -U promptinit; promptinit         # initialize prompt selector widget
prompt pure                                # select pure

# override Pure colors to use the ANSI palette . The dirty-git '*' defaults to
# a hardcoded 256-color (218); use palette red instead.
zstyle ':prompt:pure:git:dirty' color yellow
zstyle ':prompt:pure:git:branch' color default
zstyle ':prompt:pure:host' color 8
zstyle ':prompt:pure:user' color 8
zstyle ':prompt:pure:virtualenv' color 8

# print newline after command but not first line
new-line() {
	if [ -z "$NEW_LINE_BEFORE_PROMPT" ]; then
		NEW_LINE_BEFORE_PROMPT=1
	elif [ "$NEW_LINE_BEFORE_PROMPT" -eq 1 ]; then
		echo ""
	fi
}
autoload -Uz add-zsh-hook
add-zsh-hook precmd new-line

alias clear="unset NEW_LINE_BEFORE_PROMPT && clear" # redefine clear so that it does not add newline
# <--

# vim mode -->
bindkey -v              # enable vi mode
export KEYTIMEOUT=1     # do not wait to enter vi mode

# bindkey "^H" backward-delete-char
bindkey "^?" backward-delete-char
bindkey -M viins "^[[3~" delete-char

# change cursor shape for different vi modes.
beam-cursor() { echo -ne '\e[6 q' }
block-cursor() { echo -ne '\e[2 q' }
function switch-cursor () {
	case $KEYMAP in
		vicmd) block-cursor;;             # block cursor in normal mode
		viins|main) beam-cursor;;         # beam cursor in command mode
	esac
}
zle -N switch-cursor
zle -N beam-cursor
add-zle-hook-widget zle-keymap-select switch-cursor  # switch cursor whenever modes are switched
add-zle-hook-widget zle-line-init beam-cursor        # use beam cursor whenever a line is initialized
add-zsh-hook preexec beam-cursor

# use existing string to search history also in vi mode
bindkey -M vicmd "k" up-line-or-beginning-search
bindkey -M vicmd "j" down-line-or-beginning-search

# edit line in vim with ctrl-e:
autoload edit-command-line; zle -N edit-command-line
bindkey '^e' edit-command-line
bindkey -M vicmd '^[[3~' vi-delete-char
bindkey -M visual '^[[3~' vi-delete
bindkey -M vicmd '^e' edit-command-line
# <--

# plugins -->
# plugin management functions
function zsh-add-plugin() {
	PLUGIN_NAME=$(echo $1 | cut -d "/" -f 2)
	[ -d "$ZDOTDIR/plugins/$PLUGIN_NAME" ] || \
		git clone "https://github.com/$1.git" "$ZDOTDIR/plugins/$PLUGIN_NAME" # check if the plugin directory exists or clone it
	source "$ZDOTDIR/plugins/$PLUGIN_NAME/$PLUGIN_NAME.plugin.zsh" || \
		source "$ZDOTDIR/plugins/$PLUGIN_NAME/$PLUGIN_NAME.zsh"               # source the plugin
}

function zsh-update-plugins() {
	for d in $ZDOTDIR/plugins/*(/N); do
		[[ -d $d/.git ]] && { print -P "%F{4}↻%f ${d:t}"; git -C $d pull --ff-only; }
	done
}

# fzf-tab -->
zsh-add-plugin "Aloxaf/fzf-tab"

bindkey -M viins '^I' fzf-tab-complete

zstyle ':fzf-tab:*' use-fzf-default-opts yes
zstyle ':fzf-tab:*' switch-group '^' '+'
zstyle ':fzf-tab:*' continuous-trigger '/'
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls -p --color=always -- "$realpath" 2>/dev/null'
zstyle ':fzf-tab:complete:*:*' fzf-preview \
	'[[ -d "$realpath" ]] && ls -p --color=always -- "$realpath" 2>/dev/null || bat --color=always --style=plain -- "$realpath" 2>/dev/null || true'
# <--

# zsh-autosuggestions -->
zsh-add-plugin "zsh-users/zsh-autosuggestions"
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=8"          # recessive grey (matches the editor palette)
ZSH_AUTOSUGGEST_STRATEGY=(completion history)
ZSH_AUTOSUGGEST_USE_ASYNC=1
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=30              # no suggestions on very long lines

# accept with <C-Y>
bindkey -M viins '^Y' autosuggest-accept
# <--

# zsh-syntax-highlighting -->
zsh-add-plugin "zsh-users/zsh-syntax-highlighting"

# Map onto the same ANSI slots as the editor: command position blue; strings
# green; comments yellow; existing paths magenta (+underline); globs cyan;
ZSH_HIGHLIGHT_HIGHLIGHTERS+=(brackets)
typeset -gA ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[command]='fg=4'                  # first word: the command
ZSH_HIGHLIGHT_STYLES[builtin]='fg=4'
ZSH_HIGHLIGHT_STYLES[function]='fg=4'
ZSH_HIGHLIGHT_STYLES[alias]='fg=4'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=4'               # sudo, command, ...
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=2'   # strings
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=2'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=2'
ZSH_HIGHLIGHT_STYLES[comment]='fg=3'                  # comments
ZSH_HIGHLIGHT_STYLES[path]='underline'           
ZSH_HIGHLIGHT_STYLES[globbing]='fg=6'                 # * ? [ ]
ZSH_HIGHLIGHT_STYLES[unknown-token]='none'            # command-not-found: calm (no red)
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='none'     # -x
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='none'     # --xyz
ZSH_HIGHLIGHT_STYLES[commandseparator]='none'         # ; | && ||
ZSH_HIGHLIGHT_STYLES[redirection]='none'              # > < >>
ZSH_HIGHLIGHT_STYLES[reserved-word]='none'            # if/for/then
ZSH_HIGHLIGHT_STYLES[default]='none'                  # args/subcommands stay calm
ZSH_HIGHLIGHT_STYLES[cursor-matchingbracket]='fg=10,underline'
ZSH_HIGHLIGHT_STYLES[bracket-level-1]='fg=8'
ZSH_HIGHLIGHT_STYLES[bracket-level-2]='fg=8'
ZSH_HIGHLIGHT_STYLES[bracket-level-3]='fg=8'
ZSH_HIGHLIGHT_STYLES[bracket-level-4]='fg=8'
ZSH_HIGHLIGHT_STYLES[bracket-error]='fg=8'
# <--
# <--

# homebrew -->
export HOMEBREW_NO_AUTO_UPDATE=1
# <--

# misc -->
# clear half the screen
#
# TODO: Fix this
clear-half() {
	CURSOR_PREV="$CURSOR"
	HALFLINES=$(( (LINES-1)/2 ))
	for i in {1..$HALFLINES}; do echo; done
	if [[ $? -eq 0 ]]; then
		tput cup $(( HALFLINES )) $((CURSOR_PREV + 2))
	else
		tput cup $(( LINES - HALFLINES )) $((CURSOR_PREV + 3 + $#?))
	fi
}
zle -N clear-half
bindkey -M vicmd "zz" clear-half
# <--
