
start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = false

[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 5
inner.vertical =   5
outer.left =       5
outer.bottom =     5
outer.top =        5
outer.right =      5

[mode.main.binding]
alt-ctrl-cmd-period = 'layout tiles horizontal vertical'
alt-ctrl-cmd-comma = 'layout accordion horizontal vertical'

alt-ctrl-cmd-h = 'focus left'
alt-ctrl-cmd-j = 'focus down'
alt-ctrl-cmd-k = 'focus up'
alt-ctrl-cmd-l = 'focus right'

alt-ctrl-cmd-m = 'focus-monitor --wrap-around next'
alt-ctrl-cmd-shift-m = 'move-node-to-monitor --wrap-around next'

alt-ctrl-cmd-shift-h = 'move left'
alt-ctrl-cmd-shift-j = 'move down'
alt-ctrl-cmd-shift-k = 'move up'
alt-ctrl-cmd-shift-l = 'move right'

# slash is really - and rightSquareBracket is really +
alt-ctrl-cmd-slash = 'resize smart -50'
alt-ctrl-cmd-rightSquareBracket = 'resize smart +50'

alt-ctrl-cmd-0 = 'workspace 0'
alt-ctrl-cmd-1 = 'workspace 1'
alt-ctrl-cmd-2 = 'workspace 2'
alt-ctrl-cmd-3 = 'workspace 3'
alt-ctrl-cmd-4 = 'workspace 4'
alt-ctrl-cmd-5 = 'workspace 5'
alt-ctrl-cmd-6 = 'workspace 6'
alt-ctrl-cmd-7 = 'workspace 7'
alt-ctrl-cmd-8 = 'workspace 8'
alt-ctrl-cmd-9 = 'workspace 9'

alt-ctrl-cmd-shift-0 = 'move-node-to-workspace 0'
alt-ctrl-cmd-shift-1 = 'move-node-to-workspace 1'
alt-ctrl-cmd-shift-2 = 'move-node-to-workspace 2'
alt-ctrl-cmd-shift-3 = 'move-node-to-workspace 3'
alt-ctrl-cmd-shift-4 = 'move-node-to-workspace 4'
alt-ctrl-cmd-shift-5 = 'move-node-to-workspace 5'
alt-ctrl-cmd-shift-6 = 'move-node-to-workspace 6'
alt-ctrl-cmd-shift-7 = 'move-node-to-workspace 7'
alt-ctrl-cmd-shift-8 = 'move-node-to-workspace 8'
alt-ctrl-cmd-shift-9 = 'move-node-to-workspace 9'

alt-ctrl-cmd-tab = 'workspace-back-and-forth'
alt-ctrl-cmd-shift-tab = 'move-node-to-workspace --focus-follows-window --wrap-around next'

alt-ctrl-cmd-shift-semicolon = 'mode service'

[workspace-to-monitor-force-assignment]
0 = 'main'
1 = 'main'
2 = 'main'
3 = 'main'
4 = 'main'
5 = 'secondary'
6 = 'secondary'
7 = 'secondary'
8 = 'secondary'
9 = 'secondary'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

alt-ctrl-cmd-shift-h = ['join-with left', 'mode main']
alt-ctrl-cmd-shift-j = ['join-with down', 'mode main']
alt-ctrl-cmd-shift-k = ['join-with up', 'mode main']
alt-ctrl-cmd-shift-l = ['join-with right', 'mode main']

down = 'volume down'
up = 'volume up'
shift-down = ['volume set 0', 'mode main']

[[on-window-detected]]
if.app-id = 'org.pqrs.Karabiner-Elements.Settings'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'org.pqrs.Karabiner-EventViewer'
run = 'layout floating'

